export const MODAL_TYPES = {
  POST_CREATOR: 'POST_CREATOR',
  POST_DETAIL: 'POST_DETAIL',
  POST_ACTIONS: 'POST_ACTIONS',
  COMMENT_ACTIONS: 'COMMENT_ACTIONS',
  NEW_MESSAGE: 'NEW_MESSAGE',
  UNFOLLOW: 'UNFOLLOW'
};
